export {default as SignUp} from './authentication/SignUp';
export {default as SignIn} from './authentication/SignIn';
export {default as Main} from '../pages/Main';
export {default as Model} from './model/board/Model';
export {default as Description} from './model/board/Description';
export {default as ExecuteModel} from './model/execute/ExecuteModel';
export {default as CreateModel} from './model/create/CreateModel';
export {default as CreateDescription} from './model/create/CreateDescription';
export {default as SetParameter} from '../pages/model/create/SetParameter';
export {default as Account} from './profile/Account';
export {default as Payment} from './profile/Payment';
export {default as ChangePassword} from './profile/ChangePassword';
export {default as WebSocket} from './Websocket'
export {default as TarFile} from './model/menu/TarFile';
export {default as Dockerfile} from './model/menu/Dockerfile';